name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build plugin
              run: |
                  npm ci
                  npm run build

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      main.js
                      manifest.json
                      styles.css
                  tag_name: ${{ github.ref_name }}
                  prerelease: false
                  draft: false
